### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by moneeb777** [google/tpm-js#1]
Hi,

I get the following errors when building:

> root@ubuntu:/opt/tpm-js/build-web# emconfigure cmake ..
> CMake Warning at third_party/googletest.cmake:22 (message):
>   Missing GOOGLEMOCK module
> Call Stack (most recent call first):
>   CMakeLists.txt:81 (include)
> 
> 
> CMake Warning at third_party/googletest.cmake:34 (message):
>   Missing GOOGLETEST module
> Call Stack (most recent call first):
>   CMakeLists.txt:81 (include)
> 
> 
> CMake Warning at third_party/ssl.cmake:39 (message):
>   Missing BoringSSL module
> Call Stack (most recent call first):
>   CMakeLists.txt:82 (include)
> 
> 
> -- Configuring done
> CMake Error at third_party/tpm2tss.cmake:25 (add_library):
>   Cannot find source file:
> 
>     /opt/tpm-js/third_party/tpm2-tss/src/util/log.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> Call Stack (most recent call first):
>   CMakeLists.txt:84 (include)
> 
> 
> CMake Error: Cannot determine link language for target "tpm2tss_lib".
> CMake Error: CMake can not determine linker language for target: tpm2tss_lib
> -- Generating done
> -- Build files have been written to: /opt/tpm-js/build-web
> ERROR:root:Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/opt/emsdk/node/8.9.1_64bit/bin/node" .. -DCMAKE_TOOLCHAIN_FILE=/opt/emsdk/emscripten/1.38.12/cmake/Modules/Platform/Emscripten.cmake at /opt/tpm-js/build-web

**Comment by cfircohen** [comment]
Please `git submodules update --init` and try again. This pulls the third party libraries into third_party/.

**Comment by cfircohen** [comment]
I didn't include the git submodules correctly when I exported this repo. I fixed it now, please clone and try again.

**Comment by cfircohen** [comment]
Please reopen if there are additional issues.
