### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by vieiralc** [google/tpm-js#11]
after building successfully with `emcmake cmake ..` I get the following output:

```
-- Could NOT find Threads (missing: Threads_FOUND)
-- Could NOT find Threads (missing: Threads_FOUND)
-- Patching BoringSSL CMakeLists.txt
-- Configuring done
-- Generating done
-- Build files have been written to: %userPath%/tpm-js
```

Then I try to run `make -j4` but I get the following error message:

**make: *** No targets specified and no makefile found.  Stop.**

I tryied running `make -j4` on the build-web/ folder and also in tpm-js folder. In both cases I get the same error.

Am I missing something?

**PS: after the building my build-web/ folder continues empty, Is this the expected behaviour?**

**Comment by cfircohen** [comment]
Thanks for submitting this issue.

Did you update all your git submodules? You may need to run "git submodule update --init" first.

**Comment by vieiralc** [comment]
> Thanks for submitting this issue.
> 
> Did you update all your git submodules? You may need to run "git submodule update --init" first.

Yes, I did run `git submodule update --init` 

I forgot to mention that I'm using windows. I just saw another issue related to that (Compilation on windows #3) and a user just built npm-js on a ubuntu machine. I'll try that for now

**Comment by cfircohen** [comment]
Please reopen if you still experience issues with the build.
