### ISSUE TITLE
Compilation on windows

### ISSUE THREAD

**Issue by aliraees1993** [google/tpm-js#3]
Hi 

I did all the steps but am stuck with make -j4 on windows. Can you tell me the how to execute this command on windows

**Comment by cfircohen** [comment]
Hi,
Sorry, I don't have access to a Windows machine and I don't know what is required to support a native Window build.

**Comment by aliraees1993** [comment]
Also can you clarify if the correct command is 

git submodules update --init

or 

git submodule update --init

**Comment by aliraees1993** [comment]
Just to point out i compiled it in ubuntu and the compiled version works in windows.  :)

Also can you close the thread

**Comment by aliraees1993** [comment]
i might sound silly but can i want some information regarding something. i know its not the right place to ask. 

I am trying to use tpm as security device for fido.
https://medium.com/@herrjemand/verifying-fido-tpm2-0-attestation-fc7243847498

But the code defined here is in javascript. I was wondering how to make the code in site above work with emulator. If you can guide me it will be really helpful. Like is there a javascript version of tpm2-tss? How do i make it running

**Comment by cfircohen** [comment]
Most libraries here are written in C/C++ (ibmswtpm, tpm2-tss). They're compiled to WebAssembly bytecode, and then executed in the wasm framework in the browser. The javascript part is just the glue that connects the html UI to the wasm executable. I'm not familiar with FIDO, so I'm afraid I can't help you there.

**Comment by cfircohen** [comment]
Thanks for your notes.
