### ISSUE TITLE
Error in GetPublicRSA

### ISSUE THREAD

**Issue by ionut-arm** [google/tpm-js#9]
Hi,

Looking through your code for creating TPM keys I found a slight error in a logic condition in [GetPublicRSA](https://github.com/google/tpm-js/blob/master/src/app.cc#L106). The `restricted` flag should be set if the key is to be restricted, but not when both sign and decrypt are set. 
From the spec: 
> When  both  sign  and  decrypt  are  SET,  restricted  shall    be    CLEAR    and scheme shall    be TPM_ALG_NULL

**Comment by cfircohen** [comment]
Hi, thanks for your feedback!

You're right, and this is demonstrated in the keys tutorial (https://google.github.io/tpm-js/#pg_keys).
Copied from https://github.com/google/tpm-js/blob/master/html/templates/keys.html#L303:

  // A restricted key cannot be used for both encryption and signing.
  var key = app.CreatePrimary(TPM2_RH_OWNER, TPM2_ALG_RSA,/*restricted=*/1, /*decrypt=*/1, /*sign=*/1);
  assert(key.rc == TPM2_RC_P + TPM2_RC_2 + TPM2_RC_ATTRIBUTES, 'CreatePrimary expected to fail');
